In [1]:
import numpy as np

In [4]:
a=np.array([1,2,3])

In [5]:
a[0]

1

In [6]:
a[1]

2

In [7]:
import numpy as np

In [8]:
import time
import sys

In [9]:
l = range(1000)

In [10]:
l

range(0, 1000)

In [11]:
print(sys.getsizeof(5)*len(l))

28000


In [12]:
array = np.arange(1000)

In [13]:
print(array.size*array.itemsize)

4000


In [15]:
SIZE = 1000000

l1 = range(SIZE)
l2 = range(SIZE)

a1 = np.arange(SIZE)
a2 = np.arange(SIZE)

#Python list
start = time.time()
result = [(x+y) for x,y in zip(l1,l2)]
print("Python list took:",(time.time() - start)*1000)

#numpy list
start = time.time()
result = a1+a2
print("numpy took:",(time.time() - start)*1000)


Python list took: 188.62533569335938
numpy took: 13.008356094360352


In [16]:
a1 = np.array([1,2,3])
a2 = np.array([3,4,5])
a1+a2


array([4, 6, 8])

In [17]:
a1-a2

array([-2, -2, -2])

In [18]:
a= np.array([5,6,9])

In [21]:
a= np.array([[5,6,8],[7,8,9]])

In [22]:
a.ndim

2

In [23]:
a.itemsize

4

In [24]:
a.dtype

dtype('int32')

In [25]:
a= np.array([[5,6,8],[7,8,9]],dtype=np.float64)

In [26]:
a.dtype

dtype('float64')

In [27]:
a.size

6

In [28]:
a

array([[ 5.,  6.,  8.],
       [ 7.,  8.,  9.]])

In [29]:
a.shape

(2, 3)

In [30]:
a= np.array([[5,6,8],[7,8,9]],dtype=np.complex)

In [31]:
a.dtype

dtype('complex128')

In [32]:
a

array([[ 5.+0.j,  6.+0.j,  8.+0.j],
       [ 7.+0.j,  8.+0.j,  9.+0.j]])

In [33]:
np.zeros((3,4))

array([[ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.]])

In [34]:
np.ones((3,4))

array([[ 1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.]])

In [35]:
l = range(0,5)

In [38]:
print(l)

range(0, 5)


In [37]:
np.arange(1,5)

array([1, 2, 3, 4])

In [39]:
np.arange(1,5,2)

array([1, 3])

In [41]:
np.linspace(1,5,10)

array([ 1.        ,  1.44444444,  1.88888889,  2.33333333,  2.77777778,
        3.22222222,  3.66666667,  4.11111111,  4.55555556,  5.        ])

In [42]:
np.linspace(1,5,5)

array([ 1.,  2.,  3.,  4.,  5.])

In [43]:
np.linspace(1,5,20)

array([ 1.        ,  1.21052632,  1.42105263,  1.63157895,  1.84210526,
        2.05263158,  2.26315789,  2.47368421,  2.68421053,  2.89473684,
        3.10526316,  3.31578947,  3.52631579,  3.73684211,  3.94736842,
        4.15789474,  4.36842105,  4.57894737,  4.78947368,  5.        ])

In [44]:
a

array([[ 5.+0.j,  6.+0.j,  8.+0.j],
       [ 7.+0.j,  8.+0.j,  9.+0.j]])

In [45]:
a= np.array([[1,2],[3,4],[5,6]])

In [46]:
a

array([[1, 2],
       [3, 4],
       [5, 6]])

In [47]:
a.shape

(3, 2)

In [48]:
a.reshape(2,3)

array([[1, 2, 3],
       [4, 5, 6]])

In [49]:
a.reshape(6,1)

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

In [50]:
a.ravel()

array([1, 2, 3, 4, 5, 6])

In [51]:
a

array([[1, 2],
       [3, 4],
       [5, 6]])

In [52]:
a.min()

1

In [53]:
a.max()

6

In [54]:
a.sum()

21

In [57]:
a.sum(axis = 0)

array([ 9, 12])

In [58]:
a.sum(axis = 1)

array([ 3,  7, 11])

In [59]:
np.sqrt(a)

array([[ 1.        ,  1.41421356],
       [ 1.73205081,  2.        ],
       [ 2.23606798,  2.44948974]])

In [60]:
np.std(a)

1.707825127659933

In [61]:
a= np.array([[1,1],[0,1]])

In [62]:
a= np.array([[1,2],[3,4]])

In [63]:
b= np.array([[5,6],[7,8]])


In [64]:
a+b

array([[ 6,  8],
       [10, 12]])

In [65]:
a-b

array([[-4, -4],
       [-4, -4]])

In [66]:
a*b

array([[ 5, 12],
       [21, 32]])

In [67]:
a/b

array([[ 0.2       ,  0.33333333],
       [ 0.42857143,  0.5       ]])

In [68]:
a%b

array([[1, 2],
       [3, 4]], dtype=int32)

In [69]:
a.dot(b)

array([[19, 22],
       [43, 50]])

In [71]:
n = [6,7,8]
n[0:2]

[6, 7]

In [72]:
a= np.array([6,7,8])


In [73]:
a[0:2]

array([6, 7])

In [74]:
a[-1]

8

In [75]:
a = np.array([[6,7,8],[1,2,3],[9,3,2]])

In [76]:
a

array([[6, 7, 8],
       [1, 2, 3],
       [9, 3, 2]])

In [77]:
a[1,2]

3

In [78]:
a[0:2]

array([[6, 7, 8],
       [1, 2, 3]])

In [79]:
a[0:2,2]

array([8, 3])

In [80]:
a[-1]

array([9, 3, 2])

In [81]:
a[-1,0:2]

array([9, 3])

In [83]:
a[:,1:3]

array([[7, 8],
       [2, 3],
       [3, 2]])

In [84]:
a

array([[6, 7, 8],
       [1, 2, 3],
       [9, 3, 2]])

In [85]:
for row in a:
    print(row)

[6 7 8]
[1 2 3]
[9 3 2]


In [86]:
for cell in a.flat:
    print(cell)

6
7
8
1
2
3
9
3
2


In [87]:
a= np.arange(6).reshape(3,2) 

In [88]:
b= np.arange(6,12).reshape(3,2) 

In [89]:
a


array([[0, 1],
       [2, 3],
       [4, 5]])

In [90]:
b

array([[ 6,  7],
       [ 8,  9],
       [10, 11]])

In [91]:
np.vstack((a,b))

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11]])

In [92]:
np.hstack((a,b))

array([[ 0,  1,  6,  7],
       [ 2,  3,  8,  9],
       [ 4,  5, 10, 11]])

In [93]:
a= np.arange(30).reshape(2,15)

In [94]:
a

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])

In [96]:
np.hsplit(a,3)

[array([[ 0,  1,  2,  3,  4],
        [15, 16, 17, 18, 19]]), array([[ 5,  6,  7,  8,  9],
        [20, 21, 22, 23, 24]]), array([[10, 11, 12, 13, 14],
        [25, 26, 27, 28, 29]])]

In [97]:
result = np.hsplit(a,3)

In [98]:
result[0]

array([[ 0,  1,  2,  3,  4],
       [15, 16, 17, 18, 19]])

In [99]:
result[1]

array([[ 5,  6,  7,  8,  9],
       [20, 21, 22, 23, 24]])

In [100]:
result[2]

array([[10, 11, 12, 13, 14],
       [25, 26, 27, 28, 29]])

In [101]:
result = np.vsplit(a,2)

In [102]:
result[0]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14]])

In [103]:
result[1]

array([[15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29]])

In [104]:
a= np.arange(12).reshape(3,4)

In [105]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [106]:
b= a>4

In [107]:
b

array([[False, False, False, False],
       [False,  True,  True,  True],
       [ True,  True,  True,  True]], dtype=bool)

In [108]:
a[b]

array([ 5,  6,  7,  8,  9, 10, 11])

In [109]:
a[b] = -1

In [110]:
a

array([[ 0,  1,  2,  3],
       [ 4, -1, -1, -1],
       [-1, -1, -1, -1]])